
alias gffs='git flow feature start'
alias gfff='git flow feature finish'
alias gfrs='git flow release start'
alias gfrf='git flow release finish'
alias gfhs='git flow hotfix start'
alias gfhf='git flow hotfix finish'
alias gfbs='git flow bugfix start'
alias gfbf='git flow bugfix finish'
alias gv='gitversion'

alias gffs='git flow feature start'
alias gfff='git flow feature finish'
alias gfrs='git flow release start'
alias gfrf='git flow release finish'
alias gfhs='git flow hotfix start'
alias gfhf='git flow hotfix finish'
alias gfbs='git flow bugfix start'
alias gfbf='git flow bugfix finish'
alias gv='gitversion'

alias gffs='git flow feature start'
alias gfff='git flow feature finish'
alias gfrs='git flow release start'
alias gfrf='git flow release finish'
alias gfhs='git flow hotfix start'
alias gfhf='git flow hotfix finish'
alias gfbs='git flow bugfix start'
alias gfbf='git flow bugfix finish'
alias gv='gitversion'
